baseURL: https://webmin.com/
# baseURL: https://webmin.dev/
languageCode: en-us
title: Webmin
theme: PaperMod

module:
  mounts:
  - source: layouts
    target: layouts
  - source: layouts/docs/list.html
    target: layouts/docs/single.html

canonifyURLs: true

menu:
  main:
    - identifier: download
      name: Download
      url: /download/
      weight: 10
    - identifier: changelog
      name: Changelog
      url: /archives/
      weight: 20
    - identifier: faq
      name: FAQ
      url: /faq/
      weight: 30
    - identifier: wiki
      name: 'Documentation'
      url: /docs/
      weight: 40
    - identifier: forum
      name: 'Forum'
      url: https://forum.virtualmin.com/c/webmin/12
      weight: 50

minify:
  minifyOutput: true

enableRobotsTXT: true
#robotsNoIndex: true

params:
  version: 
    webmin: '2.202'
    usermin: '2.102'

  env: production

  title: Webmin
  description: "Powerful and flexible web-based server management control panel"
  keywords: [webmin, usermin, virtualmin, cloudmin, linux, system administration]
  author: Jamie Cameron

  # hide default footer
  hideFooter: true

  # allow disabling for some
  # pages with custom option
  hideEditPost: false
  # edit posts
  editPost:
    URL: "https://github.com/webmin/webmin.com/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # home-info mode
  homeInfoParams:
    Title: "What is Webmin?"
    content: >
        Webmin is a web-based system administration tool for Unix-like servers, 
        and services with about 1,000,000 yearly installations worldwide. Using it,
        it is possible to configure operating system internals, such as users, disk
        quotas, services or configuration files, as well as modify, and control
        open-source apps, such as **BIND** DNS Server, **Apache** HTTP Server, 
        **PHP**, **MySQL**, and many more.
  
  # we always need the container
  socialIcons:
    - name: github
      url: "https://github.com/webmin/webmin"

  # we need to respect user OS preferences in terms of chosen color palette
  defaultTheme: auto
  disableThemeToggle: false
  
  ShowReadingTime: true
  
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # Embed Webmin logo nicely
  label:
    text: " "
    iconSVG: '<svg width="180px" height="35px" version="1.0" viewBox="0 0 515.66 100.54" xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><metadata><rdf:RDF><cc:Work rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/></cc:Work></rdf:RDF></metadata><g transform="translate(-14.721 -55.382)"><g transform="matrix(.9803 0 0 1.0201 1.7678 -7.0795)" stroke-width="1.0297" aria-label="webmin"><path d="m145.24 95.55v20.66c0 3.7563 0.59311 7.1173 1.8782 10.083s3.0644 5.5356 5.338 7.6115c2.1747 2.1747 4.7448 3.7563 7.7104 4.9426 2.8667 1.1862 5.931 1.7793 9.292 1.7793 3.5586 0 6.8207-0.5931 9.7862-1.977s5.6345-3.2621 8.0069-5.8322c2.1747 2.4713 4.8437 4.3494 8.0069 5.7334 3.0644 1.3839 6.3264 2.0759 9.7862 2.0759 3.1632 0 6.3264-0.5931 9.292-1.7793 2.9655-1.1862 5.5356-2.7678 7.7104-4.9426s3.954-4.7448 5.338-7.7104c1.2851-2.9655 1.977-6.3265 1.977-9.9839v-20.66c0-1.6805-0.69196-3.1632-1.8782-4.4483-1.2851-1.1862-2.7678-1.8782-4.4483-1.8782-1.7793 0-3.2621 0.69196-4.4483 1.8782-1.2851 1.2851-1.8782 2.7678-1.8782 4.4483v21.747c0 3.7563-1.1862 6.623-3.3609 8.6989-2.2736 2.0759-5.0414 3.0644-8.3035 3.0644-1.5816 0-3.0644-0.19771-4.4483-0.79081-1.3839-0.49426-2.669-1.2851-3.6575-2.2736s-1.8782-2.2736-2.4713-3.7563c-0.59311-1.3839-0.88966-3.0644-0.88966-4.9425v-21.747c0-1.6805-0.69196-3.1632-1.8782-4.4483-1.2851-1.1862-2.7678-1.8782-4.4483-1.8782-1.7793 0-3.2621 0.69196-4.4483 1.8782-1.1862 1.2851-1.7793 2.7678-1.7793 4.4483v21.747c0 1.8782-0.39541 3.5586-0.98851 4.9425-0.59311 1.4828-1.4828 2.7678-2.4713 3.7563-0.98851 0.98851-2.2736 1.7793-3.6575 2.2736-1.3839 0.5931-2.8667 0.79081-4.4483 0.79081-3.3609 0-6.2276-0.98851-8.4023-3.1632-2.1747-2.0759-3.2621-4.9426-3.2621-8.6v-21.747c0-1.6805-0.69196-3.1632-1.8782-4.4483-1.2851-1.1862-2.7678-1.8782-4.4483-1.8782-1.7793 0-3.2621 0.69196-4.4483 1.8782-1.1862 1.2851-1.7793 2.7678-1.7793 4.4483z"/><path d="m252.89 119.97h29.556c2.0759 0 3.8552-0.69195 5.2391-2.0759 1.3839-1.3839 2.1747-3.1632 2.1747-5.3379 0-2.8667-0.69195-5.7334-1.8782-8.5012-1.2851-2.7678-2.9655-5.2391-5.1402-7.4138s-4.8437-3.8552-7.8092-5.2391-6.2276-2.0759-9.6874-2.0759c-3.5586 0-6.8207 0.69196-9.8851 1.977-3.1632 1.3839-5.8322 3.1632-8.1058 5.4368-2.3724 2.3724-4.1517 5.0414-5.5356 8.1058-1.3839 3.1632-2.0759 6.4253-2.0759 9.9839s0.5931 6.9196 1.977 10.083c1.2851 3.1632 3.0644 5.8322 5.4368 8.2046s5.1402 4.1517 8.3035 5.5356c3.1632 1.3839 6.5242 1.977 10.28 1.977 2.3724 0 4.4483-0.0988 6.2276-0.3954 1.7793-0.1977 3.2621-0.59311 4.646-0.98851 1.2851-0.3954 2.3724-0.79081 3.1632-1.1862 0.79081-0.39541 1.4828-0.79081 1.977-1.0874 0.88966-0.59311 1.6805-1.3839 2.3724-2.2736 0.59311-0.88966 0.98851-1.977 0.98851-3.3609 0-1.5816-0.5931-2.8667-1.6805-3.954-1.1862-0.98851-2.5701-1.5816-4.1517-1.5816s-3.0644 0.49425-4.5471 1.4828c-0.79081 0.59311-1.8782 0.98851-3.3609 1.3839-1.4828 0.39541-3.3609 0.59311-5.6345 0.59311-1.4828 0-2.9655-0.1977-4.3494-0.69196-1.3839-0.3954-2.669-1.0874-3.8552-1.8782s-2.1747-1.7793-2.9655-2.9655c-0.88966-1.1862-1.4828-2.3724-1.6805-3.7563zm12.455-19.474c1.5816 0 3.1632 0.29655 4.646 0.88965 1.4828 0.59311 2.7678 1.2851 3.8552 2.1747 1.0874 0.88966 1.977 1.8782 2.669 3.0644 0.69196 1.1862 1.1862 2.2736 1.3839 3.3609h-25.009c0.1977-1.1862 0.69195-2.2736 1.4828-3.4598 0.69196-1.0874 1.5816-2.0759 2.7678-2.9655 1.0874-0.88965 2.3724-1.5816 3.7563-2.1747s2.8667-0.88965 4.4483-0.88965z"/><path d="m300.24 71.826v62.474c0 1.7793 0.5931 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 0.7908 0 1.5816-0.0988 2.3724-0.49425 0.69195-0.29656 1.2851-0.69196 1.8782-1.2851 0.49426-0.49426 0.88966-1.0874 1.1862-1.6805 0.29656-0.59311 0.49426-1.2851 0.49426-1.8782 1.2851 1.1862 3.0644 2.3724 5.4368 3.5586 2.2736 1.1862 5.1402 1.7793 8.6989 1.7793 3.3609 0 6.623-0.5931 9.6874-1.977s5.7334-3.1632 8.0069-5.5356c2.1747-2.2736 3.954-5.0414 5.338-8.2046 1.2851-3.1632 1.977-6.5242 1.977-10.083 0-3.5586-0.69195-6.8207-2.0759-9.9839-1.3839-3.1632-3.1632-5.8322-5.5356-8.2046-2.3724-2.2736-5.0414-4.0529-8.1058-5.4368-3.0644-1.2851-6.3265-1.977-9.6874-1.977-3.2621 0-6.0299 0.5931-8.3035 1.7793s-3.954 2.3724-5.0414 3.4598v-22.637c0-1.6805-0.69195-3.1632-1.8782-4.4483-1.2851-1.1862-2.7678-1.8782-4.4483-1.8782-1.7793 0-3.2621 0.69196-4.4483 1.8782-1.2851 1.2851-1.8782 2.7678-1.8782 4.4483zm11.664 43c0-1.977 0.29656-3.7563 0.98851-5.5356 0.69196-1.6805 1.6805-3.1632 2.8667-4.4483 1.1862-1.1862 2.669-2.1747 4.3494-2.9655 1.6805-0.69196 3.5586-1.0874 5.5356-1.0874s3.7563 0.3954 5.4368 1.1862c1.6805 0.79081 3.1632 1.7793 4.4483 3.0644 1.1862 1.2851 2.1747 2.7678 2.9655 4.4483 0.69195 1.6805 1.0874 3.4598 1.0874 5.338 0 1.977-0.39541 3.7563-1.0874 5.4368-0.69196 1.7793-1.6805 3.2621-2.8667 4.5471-1.2851 1.3839-2.7678 2.3724-4.4483 3.1632-1.7793 0.7908-3.5586 1.1862-5.5356 1.1862s-3.8552-0.29656-5.5356-1.0874c-1.6805-0.69196-3.1632-1.6805-4.3494-2.9655s-2.1747-2.7678-2.8667-4.5471c-0.69195-1.7793-0.98851-3.6575-0.98851-5.7334z"/><path d="m446.14 134.3v-20.66c0-3.5586-0.69196-6.9196-1.977-9.9839-1.2851-2.9655-3.0644-5.5357-5.2391-7.7104-2.2736-2.0759-4.8437-3.7563-7.8092-4.9425s-6.0299-1.7793-9.1931-1.7793c-3.5586 0-6.9196 0.69196-9.8851 2.0759-2.9655 1.3839-5.6345 3.2621-7.9081 5.7334-2.2736-2.3724-4.9426-4.3494-8.0069-5.7334-3.1632-1.3839-6.4253-2.0759-9.7862-2.0759s-6.4253 0.5931-9.3908 1.7793-5.5356 2.8667-7.7104 5.0414-3.954 4.7448-5.2391 7.7104c-1.3839 2.9655-1.977 6.3264-1.977 9.8851v20.66c0 1.7793 0.5931 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.4483-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483v-21.747c0-3.6575 1.0874-6.5242 3.3609-8.6 2.1747-2.0759 4.9426-3.1632 8.3035-3.1632 1.5816 0 3.0644 0.29655 4.4483 0.79081 1.3839 0.5931 2.5701 1.3839 3.5586 2.3724s1.8782 2.2736 2.4713 3.6575c0.59311 1.4828 0.98851 3.1632 0.98851 4.9426v21.747c0 1.7793 0.59311 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.3494-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483v-21.747c0-1.7793 0.29656-3.4598 0.88966-4.9426 0.59311-1.3839 1.4828-2.669 2.4713-3.6575 0.9885-0.98851 2.2736-1.7793 3.6575-2.3724 1.3839-0.49426 2.9655-0.79081 4.5471-0.79081 3.3609 0 6.1288 1.0874 8.3035 3.1632 2.1747 2.1747 3.3609 5.0414 3.3609 8.6v21.747c0 1.7793 0.5931 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.3494-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483z"/><path d="m473.03 134.3v-37.761c0-1.6805-0.69195-3.1632-1.8782-4.4483-1.2851-1.1862-2.7678-1.8782-4.4483-1.8782-1.7793 0-3.2621 0.69196-4.4483 1.8782-1.2851 1.2851-1.8782 2.7678-1.8782 4.4483v37.761c0 1.7793 0.5931 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.4483-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483zm-14.037-57.136c0 2.1747 0.69196 3.954 2.2736 5.4368 1.4828 1.5816 3.2621 2.2736 5.4368 2.2736 2.0759 0 3.8552-0.69196 5.4368-2.2736 1.4828-1.4828 2.2736-3.2621 2.2736-5.4368 0-2.0759-0.79081-3.8552-2.2736-5.4368-1.5816-1.4828-3.3609-2.2736-5.4368-2.2736-2.1747 0-3.954 0.79081-5.4368 2.2736-1.5816 1.5816-2.2736 3.3609-2.2736 5.4368z"/><path d="m526.6 114.83v19.474c0 1.7793 0.59311 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.4483-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483v-19.474c0-3.5586-0.69196-6.8207-2.0759-9.9839-1.3839-3.0644-3.1632-5.7334-5.5356-8.1058s-5.1402-4.1517-8.3035-5.5356c-3.1632-1.2851-6.5242-1.977-10.083-1.977-3.6575 0-7.0184 0.69196-10.182 1.977-3.1632 1.3839-5.9311 3.1632-8.3035 5.4368-2.3724 2.3724-4.1517 5.0414-5.5356 8.2046s-1.977 6.4253-1.977 9.9839v19.474c0 1.7793 0.59311 3.2621 1.8782 4.4483 1.1862 1.2851 2.669 1.8782 4.4483 1.8782 1.6805 0 3.1632-0.5931 4.4483-1.8782 1.1862-1.1862 1.8782-2.669 1.8782-4.4483v-19.474c0-1.8782 0.29655-3.6575 0.98851-5.338 0.5931-1.6805 1.5816-3.1632 2.7678-4.4483s2.5701-2.2736 4.1517-3.0644 3.4598-1.1862 5.4368-1.1862 3.7563 0.3954 5.338 1.1862c1.5816 0.79081 3.0644 1.7793 4.2506 3.0644s2.0759 2.7678 2.7678 4.4483c0.59311 1.6805 0.98851 3.4598 0.98851 5.338z"/></g><path d="m89.712 155.26c-1.9595-0.19682-3.8581-0.75152-5.7044-1.6666-1.1733-0.58155-1.6331-0.84822-10.072-5.8415l-5.4628-3.2324-7.3547 4.1067c-7.8541 4.3855-8.6069 4.783-9.9302 5.2438-1.6577 0.5772-2.5891 0.7383-4.6412 0.80273-1.6804 0.0528-2.124 0.0282-3.3287-0.18456-3.1105-0.54929-5.9997-1.7248-8.3579-3.4007-1.1896-0.84536-3.2742-3.0493-4.0841-4.3177-2.2185-3.4747-3.2734-7.4041-3.0949-11.528 0.03596-0.83071 0.09689-1.6983 0.1354-1.9279 0.05815-0.34669 0.03567-0.42985-0.13224-0.48988-0.82586-0.29521-2.4336-1.0671-3.3797-1.6226-1.4917-0.87585-2.4031-1.5918-3.755-2.9498-4.1931-4.2119-5.9524-9.5734-5.0119-15.274 0.50928-3.0867 1.6192-5.8788 3.2467-8.1672 0.78341-1.1016 2.4542-2.8002 3.5605-3.6198 0.80231-0.5944 8.6121-5.4194 13.253-8.1877l1.8684-1.1146-0.07537-8.9504c-0.08215-9.7553-0.0596-10.335 0.48759-12.54 0.78222-3.1512 2.3563-5.8541 4.9154-8.4406 3.0226-3.0548 6.045-4.7237 9.7448-5.3805 1.8737-0.33265 5.1287-0.25586 7.0092 0.16538 2.9691 0.66508 5.8463 1.9977 8.4005 3.8908l0.72355 0.53628 1.0549-0.81808c2.8403-2.2027 5.6171-3.4674 9.0308-4.1129 1.7099-0.32334 5.0788-0.35381 6.5903-0.05964 3.7692 0.7336 6.9142 2.5 9.7786 5.4922 2.87 2.998 4.4944 6.1791 5.1753 10.135 0.23853 1.3857 0.24695 3.3304 0.0545 12.561-0.094 4.5059-0.11484 7.3979-0.0538 7.4594 0.17782 0.17933 3.2269 1.9865 8.1583 4.8354 7.4248 4.2893 7.8433 4.5704 9.7135 6.5233 2.398 2.504 3.9711 5.6684 4.7011 9.4567 0.33021 1.7135 0.36039 5.0233 0.059 6.475-0.62284 3.0005-1.8314 5.4972-3.9007 8.058-2.0406 2.5254-5.1175 4.7162-8.261 5.882l-0.96961 0.3596-0.0196 2.8984c-0.0216 3.1813-0.12995 3.9984-0.83545 6.2973-1.097 3.5746-3.4712 6.9972-6.2841 9.0591-1.2498 0.91615-3.424 2.023-5.0624 2.5773-2.7677 0.93628-5.3471 1.267-7.8896 1.0117zm4.4243-11.784c1.8838-0.65915 3.1037-1.9053 3.9232-4.0075 0.36505-0.93646 0.45026-2.4135 0.19863-3.4435-0.63313-2.5918-1.7897-3.5225-11.158-8.9796-8.6264-5.0247-8.9097-5.2049-9.9169-6.3069-1.0737-1.1748-1.5004-2.2389-1.5004-3.7416 0-1.1466 0.29948-2.1182 0.97734-3.1709 0.66523-1.0331 1.2212-1.5471 2.2001-2.0339 1.0358-0.51516 2.0735-0.68707 3.1505-0.52191 1.7548 0.2691 1.7616 0.27257 11.229 5.7286 3.8803 2.2362 7.4266 4.2313 7.8807 4.4334 1.4624 0.65106 2.977 0.98949 4.4522 0.99482 1.2374 4e-3 1.3238-0.0107 2.0263-0.3563 1.3864-0.68208 2.9425-2.5724 3.4216-4.1564 0.45358-1.4997 0.38272-3.2049-0.18509-4.4546-0.50996-1.1223-1.7244-2.256-3.9465-3.684-0.91361-0.58713-8.2605-4.9075-13.003-7.6464-3.8904-2.2469-4.5416-2.7812-5.2334-4.2944-0.73202-1.6011-0.72627-1.4932-0.61639-11.578 0.05411-4.9635 0.06285-9.7545 0.01952-10.647-0.14089-2.8964-0.55697-4.1774-1.7641-5.4313-2.3891-2.4816-6.9286-2.6171-9.1926-0.27444-1.0482 1.0846-1.661 2.4019-2.0818 4.4751-0.20117 0.99121-0.22257 1.7228-0.31739 10.852-0.07818 7.5248-0.13703 10.009-0.25447 10.739-0.40717 2.5307-2.153 4.4792-4.4706 4.9896-3.5303 0.77745-6.6774-1.3822-7.2775-4.9942-0.13589-0.81799-0.14564-2.2161-0.06825-9.7882 0.04967-4.8587 0.05326-9.5909 8e-3 -10.516-0.14464-2.96-0.55091-4.222-1.7651-5.4832-2.3891-2.4816-6.9286-2.6171-9.1926-0.27444-1.0464 1.0827-1.6566 2.3928-2.0844 4.4751-0.20622 1.0036-0.22294 1.6238-0.30005 11.132-0.05456 6.7253-0.12152 10.243-0.20168 10.593-0.47513 2.0748-1.5588 3.5921-3.3293 4.6616-0.39842 0.24068-2.0573 1.2434-3.6864 2.2283-1.6291 0.98488-4.61 2.7604-6.6242 3.9457-5.303 3.1206-6.6801 4.049-7.6667 5.1688-0.84283 0.95666-1.2522 2.1578-1.2541 3.6794-0.0023 1.7115 0.74744 3.4202 2.1124 4.8156 1.6443 1.6809 3.5857 1.9079 6.9161 0.80846 1.3384-0.44183 2.4913-1.0512 6.7857-3.5866 4.2636-2.5172 4.9789-2.9313 8.2469-4.7734 2.4491-1.3805 3.1867-1.6922 4.4547-1.8826 2.2371-0.33596 4.1226 0.53769 5.4128 2.5081 0.77996 1.1911 1.0431 2.1194 0.98584 3.4784-0.03814 0.90595-0.09185 1.1376-0.44039 1.8999-0.41817 0.91465-1.2796 1.9679-2.0725 2.5341-0.66473 0.47466-2.2635 1.4095-7.7551 4.5344-6.1279 3.487-7.4951 4.303-9.1015 5.432-1.9674 1.3828-2.7289 2.3299-3.181 3.9563-0.28103 1.0111-0.17979 2.803 0.2091 3.7006 0.6296 1.4533 2.0366 2.962 3.3488 3.5911 0.71026 0.3405 1.7097 0.60438 2.2891 0.60438 1.1058 0 3.2263-0.65177 4.8198-1.4814 1.1254-0.58593 5.4662-3.0152 10.448-5.847 6.2588-3.5578 6.4792-3.6552 8.2937-3.6665 1.8057-0.0112 2.9141 0.38888 5.8164 2.0995 13.708 8.08 15.249 8.9216 16.891 9.2272 0.9198 0.17114 2.185 0.0639 3.1242-0.26468z" stroke-linecap="round" stroke-linejoin="round" stroke-opacity="0" stroke-width="1.1646" style="paint-order:stroke fill markers"/><text style="shape-inside:url(#rect888);white-space:pre" xml:space="preserve"/></g></svg>'
    iconHeight: 35

  markup:
    highlight:
      anchorLineNos: true
      codeFences: true
      guessSyntax: true
      lineNos: true
      noClasses: false
      style: monokai
  
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


outputs:
    home:
        - HTML
        - RSS
        - JSON
